#!/usr/bin/env python3
'''
1-async_comprehension module
'''
import asyncio
from typing import List


async_generator = __import__("0-async_generator").async_generator


async def async_comprehension() -> List[float]:
    """returns list of values generated by async_generator"""
    return [value async for value in async_generator()]
